### ISSUE TITLE
[Feature] Storable configuration for important directories

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_TexTools_CLI#3]
Currently directories have to be defined manually each time it's ran. Should be configurable.

**Comment by fosspill** [comment]
https://christosmonogios.com/2017/12/02/Manage-Configuration-In-Your-NET-Core-Web-Projects-By-Using-The-IOptions-Interface/ ?

Unsure of how crossplatform this option is, but it seems to be supported with mono.

**Comment by fosspill** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=netframework-4.8

https://ibboard.co.uk/Programming/mono-special-folders.html

**Comment by fosspill** [comment]
A few thoughts about this:
It would be preferable to have multiple ways of configuring these directories:
- .xml/.json/whatnot settings file which contains the directories. If those are present then commandline argument is not required.
- Commandline arguments. Overrides settingsfile.
- If Workingdirectory matches the game directory AND argument is blank AND no settings are set then run it on the working directory.

**Comment by shinnova** [comment]
https://github.com/salaros/config-parser also seems like the perfect way to implement a config file

**Comment by fosspill** [comment]
Ready in dev branch as of 38b73b073a88263768b5a8b0c39cbbf5a1d2805d
