### ISSUE TITLE
Fix '.NET Assembly is not optimized' issue in references\xivModdingFramework.dll

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_TexTools_CLI#37]
[CodeFactor](https://www.codefactor.io/repository/github/fosspill/ffxiv_textools_cli/overview/master) found an issue: .NET Assembly is not optimized

It's currently on:
[references\xivModdingFramework.dll
](https://www.codefactor.io/repository/github/fosspill/ffxiv_textools_cli/source/master/references/xivModdingFramework.dll)

Likely built with debug. Should be rebuilt with release settings.

**Comment by shinnova** [comment]
I think this is correct. Will rebuild with release instead.

**Comment by fosspill** [comment]
This was fixed right after #30 with commit https://github.com/fosspill/FFXIV_TexTools_CLI/commit/767d652ce2d0996922d3fc1833f2f057010e161e.

This commit has been tagged to v0.3 and binaries has been updated. Please confirm and close @shinnova

**Comment by shinnova** [comment]
Yes, this has been fixed and added to the 0.3 release. Binaries are updated to now use the correctly built framework.
