### ISSUE TITLE
[ISSUE] Stringing together commands can cause corruption of gamedata

### ISSUE THREAD

**Issue by fosspill** [fosspill/FFXIV_TexTools_CLI#48]
**Describe the bug**
If you string together multiple commands the gamedata can corrupt.

I presume that this is due to disk activity not being done before starting more activity? This is purely a blind guess.

**To Reproduce**
1. Run command 'textools r && textools mpi -i mymodpack.ttmp2'
2. Start game, get error about missing datafiles

**Expected behavior**
Running the string of commands should end up with a proper working game.

**Desktop (please complete the following information):**
 - OS: Linux
 - FFXIV_TexTools_CLI Version: v0.3.5

**Suggestions**

1. Adding a problemcheck after modpack import could potentially help?
2. Adding a ```ffttcli_lock``` file with a unix timestamp in the future before starting imports(starttime + 30min fi) and  then updating it to be a few seconds after ended operation (endtime + 2min). The second command would then have to wait for this time to be reached
3. Adding some kind of disk activity check (wait for disk sync). This would likely be the cleanest way.

**Comment by shinnova** [comment]
Running the problemcheck after importing a modpack prevents the corruption from happening, so this seems to be a good solution. Will also add a flag that lets a user skip the problemcheck after import if desired.
